# Generated by Django 5.2 on 2025-05-01 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('other_content_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('content_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='other_images/')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='weverse.other')),
            ],
        ),
        migrations.AddField(
            model_name='other',
            name='weverse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='weverse.weverse'),
        ),
        migrations.CreateModel(
            name='WeverseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weverse_images/')),
                ('weverse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='weverse.weverse')),
            ],
        ),
    ]
